name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Next.js (Export to static)
        run: |
          npm run build
          npm run export

      - name: Install Capacitor
        run: npm install @capacitor/core @capacitor/cli

      - name: Initialize Capacitor
        run: |
          npx cap init "My Demo App" "com.demo.myapp" --web-dir=out

      - name: Add Android platform
        run: npx cap add android

      - name: Copy files
        run: npx cap copy

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: MyApp-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
